config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"

  get "tasks/new", to: "tasks#new"

  get "tasks/:id", to: "tasks#show", as: :task

  post "tasks", to: "tasks#create"

  get "tasks/:id/edit", to: "tasks#edit", as: :tasks_edit 

  patch "tasks/:id", to: "tasks#update"

  patch "tasks/:id/complete", to: "tasks#complete", as: :tasks_complete

  delete "tasks/:id", to: "tasks#destroy", as: :tasks_delete

end

# As a user, I can list tasks - DONE
# As a user, I can view the details of a task - DONE
# As a user, I can add a new task - DONE
# As a user, I can edit a task (mark as completed / update title & details)
# As a user, I can remove a task

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :set_task, only: [:show, :edit, :update, :destroy, :complete]

	def index
		@tasks = Task.all
	end

	def show
	end

	def new
		@task = Task.new
	end

	def create
		@task = Task.create(task_params)

		redirect_to tasks_path
	end

	def edit
	end

	def update
    @task.update(task_params)

    redirect_to tasks_path
	end

	def destroy
		@task.destroy

		redirect_to tasks_path
	end

	def complete
		@task[:completed] = true
		@task.save

		redirect_to tasks_path
  end

	private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

   <div class="form-group">
	  <%= f.check_box :completed, class: 'form-check-input' %>
	  <%= f.label :completed %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<div class="wrapper">
	<div class="container">
		<div class="action-box">
			<%= link_to "<< Back to tasks", tasks_path %>
		</div>
		
		<%= render 'form', task: @task %>

	</div>
</div>

app/views/tasks/index.html.erb
<div class="wrapper">
	<div class="container">
		<div class="cards">
			<h1>List of All Tasks</h1>
			<% @tasks.each do |task|  %>
			<div class="card">
				<% if task.completed == true %>
					<i class="far fa-check-square"></i>
				<% else %>
					<i class="far fa-square"></i>
				<% end %>
				<h3><%= link_to "#{task.title}", task_path(task)%></h3>	
			</div>
			<% end  %>
			<div class="action-box">
				<%= link_to "Add a task", tasks_new_path, class: 'btn btn-primary' %>
			</div>
		</div>
	</div>
</div>

app/views/tasks/new.html.erb
<div class="wrapper">
	<div class="container">
		<div class="action-box">
			<%= link_to "<< Back to tasks", tasks_path %>
		</div>
		
		<%= render 'form', task: @task %>

	</div>
</div>

app/views/tasks/show.html.erb
<div class="wrapper">
	<div class="container">
		<div class="action-box">
			<%= link_to "<< Back to tasks", tasks_path %>
		</div>
		<h2><%= @task.title %></h2>
		<div class="card">
			<% if @task.completed == true %>
			<i class="far fa-check-square"></i>
			<% else %>
				<i class="far fa-square"></i>
			<% end %>
			<h3><%= @task.details %></h3>
		</div>
		<div class="action-box">
			<%= link_to "Mark as complete", tasks_complete_path, method: :patch, class: 'btn btn-success' %>
			<%= link_to "Edit task", tasks_edit_path, class: 'btn btn-primary' %>
			<%= link_to "Delete task", tasks_delete_path, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
		</div>
	</div>
</div>